## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function
## This function make a special "matrix" object that can cache its inverse

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setInverse <- function(inverse) inv <<- inverse
  getInverse <- function() inv
  list(set = set,
       get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}




## Write a short comment describing this function
##This function calculates the inverse of the "matrix" generated by makeCacheMatrix 
cacheSolve <- function(x, ...) {
  inv <- x$getinverse()
     if(!is.null(inv)) {
         message("acquiring cached data")
          return(inv)
      }
  data <- x$get()
   inv <- solve(data, ...)
  x$setinverse(inv)
  inv
        ## Return a matrix that is the inverse of 'x'
}
